### ISSUE TITLE
Moving Spacecavate to being OpenSource and deciding on a licence

### ISSUE THREAD

**Issue by haennes** [GREEN-CHAOS/Spacecavate#25]
As Spacecavate should get a Open Source game (preferably under the GPL v.2.0 licence) i need ALL OF THE CONTRIBUTORS to accept the licence otherwise their code will have to be removed as they still have the right to their own Code they wrote.

**Comment by TiJayTi** [comment]
I approve that my code will be open source.

**Comment by DIAMONDUSNITRO** [comment]
I approve that the commitments i post here are open source

**Comment by Nzorejames** [comment]
I agree with continuing our work as open-sourced.

**Comment by Pawel82S** [comment]
I agree that my code will be open sourced under GPL v2

**Comment by haennes** [comment]
I agree that my code will be open sourced under GPL v2
